package com.xzaminer.app.utils

const val CAT_ID = "cat_id"
const val DIR_COLUMN_CNT = "dir_column_cnt"
const val DIR_LANDSCAPE_COLUMN_CNT = "dir_landscape_column_cnt"
const val TYPE_IMAGES = 1
const val IAP_SUB_YEARLY = "com.xzaminer.app.sub.yearly"
const val IAP_SUB_MONTHLY = "com.xzaminer.app.sub.monthly"
const val PURCHASE_TYPE_SUBSCRIPTION = "subscription"
const val QUESTION_BANK_NAME = "Question Bank"
const val QB_STATUS_IN_PROGRESS = "in_progress"
const val QB_STARTED_ON = "started_on"
const val QB_COMPLETED = "completed"
const val QB_LAST_ACCESSED = "last_accessed"
const val QB_STATUS_FINISHED = "finished"
const val QB_IMPORT_PATH = "import_path"
const val QUIZ_ID = "quiz_id"
const val IS_NEW_QUIZ = "is_new_quiz"
const val TIMER_TOTAL_TIME = "timer_total_time"
const val TIMER_RUNNING_TIME = "timer_running_time"
const val COURSE_ID = "course_id"
const val SECTION_ID = "section_id"
const val DOMAIN_ID = "domain_id"
const val VIDEO_ID = "video_id"
const val QUESTION_ID = "question_id"
const val STUDY_MATERIAL_ID = "study_material_id"
const val STUDY_MATERIAL_TYPE = "study_material_type"
const val STUDY_MATERIAL_TYPE_STUDY_MATERIAL = "study_material_type_study_material"
const val STUDY_MATERIAL_TYPE_QUESTION_BANK = "study_material_type_question_bank"
const val STUDY_MATERIAL_TYPE_VIDEO = "study_material_type_video"

const val PURCHASE_COURSE_IAP = "com.xzaminer.iap.course."
const val PURCHASE_SECTION_IAP = "com.xzaminer.iap.section."
const val PURCHASE_SECTION_STUDY_MATERIAL = "com.xzaminer.iap.studymaterial."
const val PURCHASE_TYPE_IAP = "com.xzaminer.iap"
const val PURCHASE_TYPE_TRIAL = "com.xzaminer.iap.trial"
const val PURCHASE_ID = "purchase_id"

const val VIDEO_DOWNLOAD_PROGRESS = "video_download_progress"
const val VIDEO_DOWNLOAD_NAME = "video_download_name"

const val PLAYER_AUDIOBOOK = "player_audiobook"
const val ACTION_INIT_PLAY = "com.xzaminer.player.ACTION_INIT_PLAY"
const val ACTION_PLAY = "com.xzaminer.player.ACTION_PLAY"
const val ACTION_PAUSE = "com.xzaminer.player.ACTION_PAUSE"
const val ACTION_STOP = "com.xzaminer.player.ACTION_STOP"
const val AUDIO_PLAYBACK_STATE = "audio_playback_state"
const val DOWNLOAD_URL = "download_url"
const val USERTYPE_ADMIN = "admin"
