package com.xzaminer.app.utils

const val CAT_ID = "cat_id"
const val DIR_COLUMN_CNT = "dir_column_cnt"
const val DIR_LANDSCAPE_COLUMN_CNT = "dir_landscape_column_cnt"
const val TYPE_IMAGES = 1
const val PURCHASE_TYPE_IAP = "iap"
const val IAP_SUB_YEARLY = "com.xzaminer.app.sub.yearly"
const val IAP_SUB_MONTHLY = "com.xzaminer.app.sub.monthly"
const val PURCHASE_TYPE_SUBSCRIPTION = "subscription"
const val QUESTION_BANK_NAME = "Question Bank"
const val QB_STATUS_IN_PROGRESS = "in_progress"
const val QB_STATUS_FINISHED = "finished"
const val QUIZ_ID = "quiz_id"
const val IS_NEW_QUIZ = "is_new_quiz"
const val TIMER_TOTAL_TIME = "timer_total_time"
const val TIMER_RUNNING_TIME = "timer_running_time"
const val COURSE_ID = "course_id"
const val STUDY_MATERIAL_ID = "study_material_id"
const val STUDY_MATERIAL_TYPE = "study_material_type"
const val STUDY_MATERIAL_TYPE_CONCEPT = "study_material_type_concept"
const val STUDY_MATERIAL_TYPE_REVIEW = "study_material_type_review"
const val STUDY_MATERIAL_TYPE_FLASH = "study_material_type_flash"